baseURL = 'https://kettenbeil.com/'
title = 'Kettenbeil'

defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = true

[languages]
  [languages.de]
    languageCode = 'de-DE'
    languageName = 'Deutsch ðŸ‡©ðŸ‡ª'
    contentDir = 'content/de'
    weight = 1

    [languages.de.menus]
      [[languages.de.menus.main]]
        name = 'Logos'
        pageRef = '/logos'
        weight = 10
        [[languages.de.menus.main]]
        name = 'Fotos'
        pageRef = '/fotos'
        weight = 20
        [[languages.de.menus.main]]
        name = 'Sketches'
        pageRef = '/sketches'
        weight = 30
        [[languages.de.menus.main]]
        name = 'Kontakt'
        pageRef = '/kontakt'
        weight = 40


[languages.en]
    languageCode = 'en-US'
    languageName = 'English ðŸ‡¬ðŸ‡§'
    contentDir = 'content/en'
    weight = 2

    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Logos'
        pageRef = '/logos'
        weight = 10
      [[languages.en.menus.main]]
        name = 'Photos'
        pageRef = '/fotos'
        weight = 20
      [[languages.en.menus.main]]
        name = 'Sketches'
        pageRef = '/sketches'
        weight = 30
      [[languages.en.menus.main]]
        name = 'Contact'
        pageRef = '/kontakt'
        weight = 40

[menus]
[[menus.footer]]
    name = 'github'
    url = 'https://github.com/malde11'
    weight = 10
[[menus.footer]]
    name = 'Stackoverflow'
    url = 'https://stackoverflow.com/users/16225255/malte-k'
    weight = 20
[[menus.footer]]
    name = 'youtube'
    url = 'https://youtube.com'
    weight = 30
[[menus.footer]]
    name = 'FreeCodeCamp'
    url = 'https://freecodecamp.org/malde11'
    weight = 40